version: "2"
services:
  airtouch_challenge:
    container_name: airtouch_challenge
    restart: always
    build: .
    ports:
    - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
  mongo:
    container_name: mongo
    image: mongo
    ports:
    - "27017:27017"
